export interface IndustryPack {
  id: string;
  name: string;
  icon: string; // emoji
  painPoints: string[];
  competitors: string[];
  terminology: string[]; // industry-specific terms
  promptTemplates: { label: string; prompt: string }[];
  sampleProspect: { name: string; size: string; description: string }; // for Step 4 demo generation
  productPlaceholder: string; // pre-fill text for "What do you sell?" step
}

export const INDUSTRY_PACKS: IndustryPack[] = [
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    icon: '\u{1F3ED}',
    painPoints: [
      'Inventory inaccuracy leading to stockouts and overstock across warehouses',
      'Production delays caused by unplanned downtime and scheduling gaps',
      'Lack of real-time quality tracking and defect traceability',
      'Manual data entry between shop floor systems and ERP',
      'Difficulty meeting compliance and audit requirements for regulated products',
    ],
    competitors: ['SAP', 'Oracle', 'Fishbowl', 'Epicor'],
    terminology: ['BOM (Bill of Materials)', 'OEE', 'MRP', 'work order', 'cycle count', 'lot traceability', 'shop floor control', 'first-pass yield'],
    promptTemplates: [
      { label: 'Inventory accuracy ROI', prompt: 'Build an ROI business case showing how [our product] reduces inventory inaccuracy for a mid-size manufacturer currently relying on manual cycle counts and spreadsheet-based tracking.' },
      { label: 'Competitive comparison vs SAP', prompt: 'Generate a competitive comparison of [our product] vs SAP Business One for a manufacturing company with 100-300 employees evaluating inventory and production management solutions.' },
      { label: 'Plant manager one-pager', prompt: 'Create a one-pager targeting plant managers at custom manufacturers who struggle with production scheduling delays and want real-time shop floor visibility.' },
      { label: 'Quality compliance exec summary', prompt: 'Write an executive summary for a VP of Operations at a regulated manufacturer explaining how [our product] automates lot traceability and simplifies audit preparation.' },
      { label: 'ERP migration outreach', prompt: 'Draft a 3-email cold outreach sequence targeting operations directors at manufacturers still running legacy ERP or Fishbowl, focusing on the cost of inventory inaccuracy and production downtime.' },
    ],
    sampleProspect: { name: 'Midwest Metal Fabricators', size: '180 employees', description: 'Custom metal components manufacturer' },
    productPlaceholder: 'We sell a cloud-based inventory and production management platform designed for mid-size manufacturers. It provides real-time shop floor visibility, automated cycle counting, and lot traceability to reduce inventory errors and production delays.',
  },
  {
    id: 'distribution',
    name: 'Distribution / Wholesale',
    icon: '\u{1F4E6}',
    painPoints: [
      'Warehouse pick/pack errors driving costly returns and customer churn',
      'Shipping delays from manual processes and lack of carrier integration',
      'ERP disconnection causing inventory discrepancies across locations',
      'Inability to provide real-time order status to customers',
      'High labor costs from inefficient warehouse layouts and workflows',
    ],
    competitors: ['ScanForce', 'Accellos', 'manual processes', 'Fishbowl'],
    terminology: ['EDI', 'pick/pack/ship', 'ASN (Advance Ship Notice)', '3PL', 'cross-docking', 'SKU velocity', 'wave picking', 'reorder point'],
    promptTemplates: [
      { label: 'Warehouse error reduction ROI', prompt: 'Build an ROI business case for a 120-person industrial distributor showing how barcode scanning and automated pick/pack workflows reduce warehouse errors and return rates by [X]%.' },
      { label: 'ERP integration one-pager', prompt: 'Create a one-pager for an operations manager at a wholesale distributor who is frustrated by inventory discrepancies between their warehouse and their ERP system.' },
      { label: 'Competitive comparison vs ScanForce', prompt: 'Generate a competitive comparison of [our product] vs ScanForce for a distribution company evaluating warehouse management and barcode scanning solutions.' },
      { label: 'Shipping SLA battle card', prompt: 'Create a battle card for sales reps selling into distributors who are losing customers because of late shipments and lack of real-time order tracking.' },
      { label: 'DC manager cold outreach', prompt: 'Draft a 3-email outreach sequence targeting distribution center managers at mid-size wholesalers who still rely on paper pick tickets and manual shipping processes.' },
    ],
    sampleProspect: { name: 'Great Lakes Supply Co', size: '120 employees', description: 'Industrial parts distributor' },
    productPlaceholder: 'We sell a warehouse management and shipping automation platform for distributors and wholesalers. It integrates with major ERPs to provide real-time inventory visibility, barcode-driven picking, and automated carrier selection to eliminate shipping errors.',
  },
  {
    id: 'technology',
    name: 'Software / Technology',
    icon: '\u{1F4BB}',
    painPoints: [
      'Long sales cycles due to complex buying committees and evaluation processes',
      'Difficulty differentiating from competitors in crowded categories',
      'Inability to produce personalized sales content at scale',
      'Low conversion rates from generic outbound messaging',
      'Content bottleneck between marketing and sales teams',
    ],
    competitors: ['Jasper', 'Copy.ai', 'freelancers', 'in-house content teams'],
    terminology: ['ARR', 'ACV', 'churn rate', 'product-led growth', 'land and expand', 'ICP (ideal customer profile)', 'sales velocity', 'competitive moat'],
    promptTemplates: [
      { label: 'Competitive differentiation one-pager', prompt: 'Create a one-pager for a sales rep at a B2B SaaS company who needs to differentiate [our product] from Jasper and Copy.ai in a deal where the prospect is evaluating AI content tools.' },
      { label: 'Content-at-scale ROI case', prompt: 'Build an ROI business case showing how [our product] enables a 60-person software company to produce 10x more personalized sales collateral without hiring additional content writers.' },
      { label: 'Long sales cycle battle card', prompt: 'Create a battle card for enterprise SaaS deals with 6+ month sales cycles, showing how [our product] accelerates deal velocity with tailored content for each stakeholder in the buying committee.' },
      { label: 'VP Marketing exec summary', prompt: 'Write an executive summary for a VP of Marketing at a mid-market SaaS company explaining how [our product] eliminates the content bottleneck between marketing and sales.' },
      { label: 'Tech founder cold outreach', prompt: 'Draft a 3-email cold outreach sequence targeting founders and CROs at Series A-C SaaS companies who are scaling their outbound motion and struggling with personalization.' },
    ],
    sampleProspect: { name: 'DataSync Solutions', size: '60 employees', description: 'Enterprise data integration platform' },
    productPlaceholder: 'We sell an AI-powered content generation platform for B2B sales teams. It uses your product knowledge and prospect data to create personalized one-pagers, battle cards, and outbound sequences in minutes instead of days.',
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    icon: '\u{1F4BC}',
    painPoints: [
      'Manual reporting consuming billable hours on non-revenue work',
      'Inaccurate billable hour tracking leading to revenue leakage',
      'Slow turnaround on client deliverables hurting retention',
      'Lack of visibility into project profitability until it is too late',
      'Knowledge silos between engagement teams and practice areas',
    ],
    competitors: ['Harvest', 'Monday.com', 'spreadsheets', 'manual processes'],
    terminology: ['utilization rate', 'billable hours', 'engagement letter', 'SOW (Statement of Work)', 'change order', 'realization rate', 'WIP (Work in Progress)', 'fixed-fee engagement'],
    promptTemplates: [
      { label: 'Utilization improvement ROI', prompt: 'Build an ROI business case for a 45-person consulting firm showing how [our product] increases billable utilization by automating time tracking and reducing administrative overhead.' },
      { label: 'Client deliverable one-pager', prompt: 'Create a one-pager targeting managing directors at professional services firms who lose clients due to slow deliverable turnaround and inconsistent reporting quality.' },
      { label: 'Competitive comparison vs Monday.com', prompt: 'Generate a competitive comparison of [our product] vs Monday.com and Harvest for a professional services firm evaluating project management and time tracking solutions.' },
      { label: 'Revenue leakage exec summary', prompt: 'Write an executive summary for a CFO at a consulting firm explaining how [our product] eliminates revenue leakage from unbilled hours, scope creep, and inaccurate time entries.' },
      { label: 'Partner-level cold outreach', prompt: 'Draft a 3-email outreach sequence targeting partners and practice leaders at mid-size consulting firms who suspect they are leaving revenue on the table due to manual processes.' },
    ],
    sampleProspect: { name: 'Sterling Advisory Group', size: '45 employees', description: 'Management consulting firm' },
    productPlaceholder: 'We sell a project management and time tracking platform built for professional services firms. It automates client reporting, tracks billable hours in real time, and provides project profitability visibility so firms can eliminate revenue leakage.',
  },
  {
    id: 'construction',
    name: 'Construction',
    icon: '\u{1F3D7}\uFE0F',
    painPoints: [
      'Bid inaccuracy leading to underbid projects and margin erosion',
      'Change order chaos causing disputes and delayed payments',
      'Subcontractor coordination breakdowns creating schedule overruns',
      'Document management scattered across email, paper, and shared drives',
      'Lack of real-time job costing visibility until projects are over budget',
    ],
    competitors: ['Procore', 'PlanGrid', 'manual bidding', 'Sage 300'],
    terminology: ['RFI', 'submittal', 'punch list', 'change order', 'AIA billing', 'preconstruction', 'general contractor', 'retainage'],
    promptTemplates: [
      { label: 'Bid accuracy ROI case', prompt: 'Build an ROI business case for a commercial general contractor showing how [our product] improves bid accuracy and reduces the margin lost on underbid projects by [X]%.' },
      { label: 'Change order management one-pager', prompt: 'Create a one-pager for project managers at general contractors who waste hours each week chasing change order approvals through email and paper forms.' },
      { label: 'Competitive comparison vs Procore', prompt: 'Generate a competitive comparison of [our product] vs Procore for a mid-size commercial contractor with 50-150 employees evaluating construction project management solutions.' },
      { label: 'Subcontractor coordination battle card', prompt: 'Create a battle card for sales reps selling into general contractors who struggle with subcontractor scheduling, communication, and accountability across multiple job sites.' },
      { label: 'GC owner cold outreach', prompt: 'Draft a 3-email outreach sequence targeting owners and VPs of operations at commercial general contractors who still manage bids and change orders with spreadsheets and manual processes.' },
    ],
    sampleProspect: { name: 'Ironclad Builders', size: '95 employees', description: 'Commercial general contractor' },
    productPlaceholder: 'We sell a construction project management platform for commercial contractors. It streamlines bidding, automates change order workflows, and provides real-time job costing so GCs can protect margins and keep projects on schedule.',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    icon: '\u{1F3E5}',
    painPoints: [
      'Compliance burden consuming staff time on documentation and audit prep',
      'Patient data silos between clinical, billing, and administrative systems',
      'Operational inefficiency from manual scheduling and paper-based workflows',
      'Revenue cycle management delays from claim denials and coding errors',
      'Staff burnout from administrative overload reducing quality of care',
    ],
    competitors: ['Epic', 'Cerner', 'paper processes', 'legacy platforms'],
    terminology: ['HIPAA', 'EHR/EMR', 'revenue cycle management', 'claim denial', 'prior authorization', 'interoperability', 'HL7/FHIR', 'patient portal'],
    promptTemplates: [
      { label: 'Compliance automation ROI', prompt: 'Build an ROI business case for a multi-location medical practice showing how [our product] reduces compliance documentation time by [X]% and lowers audit risk.' },
      { label: 'Data integration one-pager', prompt: 'Create a one-pager for a practice administrator at a healthcare group struggling with patient data scattered across disconnected clinical, billing, and scheduling systems.' },
      { label: 'Competitive comparison vs Epic', prompt: 'Generate a competitive comparison of [our product] vs Epic and Cerner for a mid-size healthcare organization with 100-300 employees evaluating operational efficiency solutions.' },
      { label: 'Revenue cycle exec summary', prompt: 'Write an executive summary for a CFO at a healthcare organization explaining how [our product] reduces claim denial rates and accelerates revenue cycle from patient visit to payment.' },
      { label: 'Practice manager cold outreach', prompt: 'Draft a 3-email outreach sequence targeting practice managers and COOs at multi-location medical groups who are drowning in compliance paperwork and losing revenue to claim denials.' },
    ],
    sampleProspect: { name: 'Lakeview Medical Group', size: '200 employees', description: 'Multi-location practice' },
    productPlaceholder: 'We sell a healthcare operations platform that connects clinical, billing, and administrative workflows. It automates compliance documentation, reduces claim denials, and gives practice leaders real-time visibility into operational performance.',
  },
  {
    id: 'staffing',
    name: 'Staffing',
    icon: '\u{1F465}',
    painPoints: [
      'High time-to-fill causing clients to lose patience and use competitors',
      'Candidate ghosting and dropout after placement acceptance',
      'Lack of client visibility into pipeline and placement progress',
      'Manual credential tracking and compliance verification bottlenecks',
      'Low redeployment rates from poor candidate relationship management',
    ],
    competitors: ['Bullhorn', 'JobDiva', 'Indeed', 'manual processes'],
    terminology: ['time-to-fill', 'redeployment rate', 'bill rate', 'markup', 'VMS (Vendor Management System)', 'MSP', 'credentialing', 'light industrial'],
    promptTemplates: [
      { label: 'Time-to-fill ROI case', prompt: 'Build an ROI business case for a light industrial staffing agency showing how [our product] reduces time-to-fill by [X]% and increases fill rates across open requisitions.' },
      { label: 'Client visibility one-pager', prompt: 'Create a one-pager for staffing agency owners who are losing clients because they cannot provide real-time visibility into candidate pipelines and placement progress.' },
      { label: 'Competitive comparison vs Bullhorn', prompt: 'Generate a competitive comparison of [our product] vs Bullhorn and JobDiva for a staffing agency with 30-80 employees evaluating ATS and CRM solutions.' },
      { label: 'Candidate ghosting battle card', prompt: 'Create a battle card for staffing sales reps addressing the candidate ghosting problem, showing how [our product] uses automated touchpoints and engagement scoring to reduce dropout rates.' },
      { label: 'Agency owner cold outreach', prompt: 'Draft a 3-email outreach sequence targeting owners and branch managers at light industrial and clerical staffing agencies who are frustrated with low fill rates and candidate no-shows.' },
    ],
    sampleProspect: { name: 'TalentBridge Solutions', size: '55 employees', description: 'Light industrial staffing agency' },
    productPlaceholder: 'We sell a staffing operations platform that combines ATS, CRM, and credentialing automation. It helps agencies reduce time-to-fill, prevent candidate ghosting, and give clients real-time visibility into placement progress.',
  },
  {
    id: 'logistics',
    name: 'Logistics',
    icon: '\u{1F69B}',
    painPoints: [
      'Route inefficiency increasing fuel costs and delivery times',
      'Carrier management complexity across multiple freight modes',
      'Lack of real-time shipment visibility for customers and dispatchers',
      'Manual dispatch processes causing scheduling errors and driver downtime',
      'Difficulty tracking and proving on-time delivery performance to shippers',
    ],
    competitors: ['Samsara', 'Trimble', 'manual dispatch', 'legacy TMS'],
    terminology: ['TMS (Transportation Management System)', 'LTL', 'FTL', 'BOL (Bill of Lading)', 'drayage', 'deadhead miles', 'lane optimization', 'freight broker'],
    promptTemplates: [
      { label: 'Route optimization ROI', prompt: 'Build an ROI business case for a regional LTL carrier showing how [our product] reduces deadhead miles and fuel costs by optimizing route planning and load consolidation.' },
      { label: 'Real-time visibility one-pager', prompt: 'Create a one-pager for a logistics VP at a freight carrier who is losing shipper contracts because they cannot provide real-time shipment tracking and delivery ETAs.' },
      { label: 'Competitive comparison vs Samsara', prompt: 'Generate a competitive comparison of [our product] vs Samsara and Trimble for a regional carrier with 50-150 drivers evaluating fleet management and dispatch solutions.' },
      { label: 'Carrier management exec summary', prompt: 'Write an executive summary for a COO at a logistics company explaining how [our product] simplifies multi-carrier management and reduces manual dispatch errors.' },
      { label: 'Fleet manager cold outreach', prompt: 'Draft a 3-email outreach sequence targeting fleet managers and dispatch supervisors at regional carriers who still rely on phone-based dispatch and manual load planning.' },
    ],
    sampleProspect: { name: 'CrossCountry Freight', size: '85 employees', description: 'Regional LTL carrier' },
    productPlaceholder: 'We sell a transportation management and dispatch platform for carriers and freight companies. It optimizes routes, automates dispatch, and provides real-time shipment visibility so logistics companies can reduce costs and win more shipper contracts.',
  },
  {
    id: 'financial-services',
    name: 'Financial Services',
    icon: '\u{1F3E6}',
    painPoints: [
      'Compliance reporting consuming advisor time on paperwork instead of clients',
      'Slow client onboarding process causing prospect abandonment',
      'Document management chaos with files scattered across email and drives',
      'Difficulty demonstrating value to clients during quarterly reviews',
      'Manual portfolio reporting that is error-prone and time-intensive',
    ],
    competitors: ['Fiserv', 'manual processes', 'legacy platforms', 'Orion'],
    terminology: ['AUM (Assets Under Management)', 'fiduciary', 'KYC (Know Your Customer)', 'RIA', 'compliance audit', 'custodian', 'Form ADV', 'portfolio rebalancing'],
    promptTemplates: [
      { label: 'Compliance automation ROI', prompt: 'Build an ROI business case for an independent RIA showing how [our product] reduces compliance reporting time by [X]% and lowers the risk of regulatory findings.' },
      { label: 'Client onboarding one-pager', prompt: 'Create a one-pager for a wealth management firm owner who is losing prospective clients because the onboarding process takes weeks and requires too much paperwork.' },
      { label: 'Competitive comparison vs Fiserv', prompt: 'Generate a competitive comparison of [our product] vs Fiserv and legacy platforms for an independent wealth management firm evaluating client management and compliance solutions.' },
      { label: 'Advisor productivity exec summary', prompt: 'Write an executive summary for a managing partner at a wealth management firm explaining how [our product] frees advisors to spend more time with clients by automating reporting and document management.' },
      { label: 'RIA owner cold outreach', prompt: 'Draft a 3-email outreach sequence targeting principals and managing partners at independent RIAs who are bogged down by manual compliance processes and outdated client reporting tools.' },
    ],
    sampleProspect: { name: 'Clearpath Financial', size: '30 employees', description: 'Independent wealth management firm' },
    productPlaceholder: 'We sell a client management and compliance platform for independent financial advisors and RIAs. It automates client onboarding, compliance reporting, and portfolio reviews so advisors can focus on growing relationships instead of pushing paper.',
  },
  {
    id: 'other',
    name: 'Other',
    icon: '\u270F\uFE0F',
    painPoints: [
      'Inefficient manual processes slowing down daily operations',
      'Lack of data visibility making it hard to make informed decisions',
      'Difficulty scaling operations without adding headcount',
      'Disconnected systems creating data silos and duplicate work',
      'Slow time-to-value when adopting new tools and platforms',
    ],
    competitors: [],
    terminology: ['ROI', 'KPI', 'SLA', 'workflow automation', 'digital transformation'],
    promptTemplates: [
      { label: 'General ROI business case', prompt: 'Build an ROI business case for a mid-size company showing how [our product] reduces manual work and improves operational efficiency across key workflows.' },
      { label: 'Decision-maker one-pager', prompt: 'Create a one-pager targeting a department head or VP at a growing company who needs to justify investing in [our product] to their executive team.' },
      { label: 'Competitive positioning overview', prompt: 'Generate a competitive positioning document that highlights what makes [our product] different from the alternatives a prospect is likely evaluating.' },
      { label: 'Executive summary for leadership', prompt: 'Write an executive summary for a CEO or COO at a 50-200 person company explaining how [our product] solves their biggest operational challenges and delivers measurable results.' },
      { label: 'Cold outreach sequence', prompt: 'Draft a 3-email cold outreach sequence targeting operations leaders at growing companies who are experiencing the pains of scaling with manual processes and disconnected tools.' },
    ],
    sampleProspect: { name: 'Acme Corp', size: '100 employees', description: 'Growing business' },
    productPlaceholder: 'We sell a platform that helps businesses streamline their operations and work more efficiently. It replaces manual processes with automation so teams can focus on higher-value work.',
  },
];
