import type { DocumentStyle, StyleInput } from './types';
import { resolveBrand, brandCSSVars, brandFonts, brandLogoHtml, formatMarkdown, wrapDocument } from './shared';

// ── Render ──────────────────────────────────────────────────

function render(input: StyleInput): string {
  const brand = resolveBrand(input);
  const dateStr = input.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const title = input.contentType.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  const sectionsHtml = input.sections.map(s => {
    // Extract first sentence as key takeaway
    const contentText = s.content.replace(/[#*_\-|]/g, '').trim();
    const firstSentence = contentText.split(/(?<=[.!?])\s+/)[0] || contentText.substring(0, 140);

    return `<div class="section">
      <h2 class="section-heading">${s.title}</h2>
      <div class="takeaway-box">
        <div class="takeaway-label">Key Takeaway</div>
        <div class="takeaway-text">${firstSentence}</div>
      </div>
      <div class="section-body">${formatMarkdown(s.content)}</div>
    </div>`;
  }).join('\n');

  const h1SizeLarge = (brand.h1Size + 4) + 'px';

  const css = `
    ${brandCSSVars(brand)}
    body {
      font-family: var(--brand-font-secondary);
      font-size: var(--brand-font-body-size);
      color: var(--brand-text);
      background: var(--brand-background);
      line-height: 1.75;
      -webkit-font-smoothing: antialiased;
    }
    .page {
      max-width: 840px;
      margin: 0 auto;
      padding: 80px 80px;
    }
    /* ── Cover ── */
    .cover {
      margin-bottom: 72px;
      padding-bottom: 40px;
      border-bottom: 1px solid #e0e0e0;
    }
    .cover-logo { margin-bottom: 48px; }
    .cover-title {
      font-family: var(--brand-font-primary);
      font-size: ${h1SizeLarge};
      font-weight: 700;
      color: var(--brand-primary);
      line-height: 1.15;
      margin-bottom: 16px;
      letter-spacing: -0.02em;
    }
    .cover-meta {
      font-size: 14px;
      color: #999;
      margin-top: 16px;
    }
    /* ── Sections ── */
    .section {
      margin-bottom: 64px;
      page-break-inside: avoid;
    }
    .section-heading {
      font-family: var(--brand-font-primary);
      font-size: ${h1SizeLarge};
      font-weight: 700;
      color: var(--brand-primary);
      margin-bottom: 24px;
      line-height: 1.2;
      letter-spacing: -0.01em;
    }
    /* ── Key takeaway ── */
    .takeaway-box {
      border: 2px solid var(--brand-primary);
      padding: 24px 28px;
      margin-bottom: 28px;
      background: var(--brand-background);
    }
    .takeaway-label {
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.12em;
      color: var(--brand-primary);
      margin-bottom: 8px;
    }
    .takeaway-text {
      font-family: var(--brand-font-primary);
      font-size: 18px;
      font-weight: 500;
      color: var(--brand-text);
      line-height: 1.5;
    }
    /* ── Supporting detail (de-emphasized) ── */
    .section-body {
      font-size: 13px;
      color: #777;
      line-height: 1.75;
    }
    .section-body p { margin-bottom: 12px; }
    .section-body h1, .section-body h2, .section-body h3, .section-body h4 {
      color: #555;
      margin: 20px 0 8px;
      font-weight: 600;
      font-size: 15px;
    }
    .section-body strong { font-weight: 600; color: #555; }
    .section-body ul, .section-body ol { padding-left: 20px; margin: 10px 0; }
    .section-body li { margin-bottom: 6px; }
    .section-body hr { border: none; border-top: 1px solid #eee; margin: 20px 0; }
    .section-body table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 12px;
    }
    .section-body th {
      background: #f5f5f5;
      font-weight: 600;
      text-align: left;
      padding: 8px 12px;
      border-bottom: 1px solid #ddd;
      color: #555;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .section-body td {
      padding: 8px 12px;
      border-bottom: 1px solid #f0f0f0;
    }
    /* ── Footer ── */
    .footer {
      margin-top: 60px;
      padding-top: 16px;
      border-top: 1px solid #e0e0e0;
      text-align: center;
      font-size: 11px;
      color: #bbb;
      letter-spacing: 0.02em;
    }
  `;

  const body = `
    <div class="page">
      <div class="cover">
        <div class="cover-logo">${brandLogoHtml(input, 'height:40px;')}</div>
        <div class="cover-title">${title}</div>
        <div class="cover-meta">
          Prepared for ${input.prospect.companyName}<br/>
          ${dateStr}
        </div>
      </div>
      ${sectionsHtml}
      <div class="footer">${input.companyName} | ${dateStr} | Generated by ContentForg</div>
    </div>
  `;

  return wrapDocument({ title: `${title} — ${input.prospect.companyName}`, css, body, fonts: brandFonts(brand) });
}

// ── Thumbnail ───────────────────────────────────────────────

function thumbnail(accentColor: string): string {
  return `<div style="width:100%;height:100%;background:#fff;font-family:sans-serif;padding:28px 24px;box-sizing:border-box;position:relative;">
    <div style="width:36px;height:8px;background:${accentColor};border-radius:1px;margin-bottom:24px;"></div>
    <div style="font-size:14px;font-weight:700;color:${accentColor};line-height:1.2;margin-bottom:6px;">Document Title</div>
    <div style="width:50%;height:3px;background:#ddd;border-radius:1px;margin-bottom:24px;"></div>
    <div style="border-bottom:1px solid #eee;padding-bottom:20px;margin-bottom:20px;">
      <div style="font-size:12px;font-weight:700;color:${accentColor};margin-bottom:8px;">Section One</div>
      <div style="border:2px solid ${accentColor};padding:8px 10px;margin-bottom:8px;">
        <div style="width:8px;height:3px;background:${accentColor};border-radius:1px;margin-bottom:4px;"></div>
        <div style="width:80%;height:4px;background:#ddd;border-radius:1px;margin-bottom:2px;"></div>
        <div style="width:60%;height:4px;background:#ddd;border-radius:1px;"></div>
      </div>
      <div style="width:90%;height:3px;background:#eee;border-radius:1px;margin-bottom:2px;"></div>
      <div style="width:80%;height:3px;background:#eee;border-radius:1px;"></div>
    </div>
    <div style="position:absolute;bottom:10px;left:0;right:0;text-align:center;font-size:6px;color:#ccc;">Company | Date | ContentForg</div>
  </div>`;
}

// ── Export ───────────────────────────────────────────────────

const style22Boardroom: DocumentStyle = {
  id: 'style-22',
  name: 'Boardroom',
  category: 'corporate',
  description: 'Board-level presentation — large type, one takeaway per page, minimal detail',
  keywords: ['boardroom', 'board', 'executive', 'premium', 'leave-behind'],
  render,
  thumbnail,
};

export default style22Boardroom;
