import type { DocumentStyle, StyleInput } from './types';
import { resolveBrand, brandCSSVars, brandFonts, brandLogoHtml, formatMarkdown, wrapDocument } from './shared';

// ── Render ──────────────────────────────────────────────────

function render(input: StyleInput): string {
  const brand = resolveBrand(input);
  const dateStr = input.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const title = input.contentType.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  const sectionsHtml = input.sections.map(s => {
    // Extract first sentence as executive takeaway
    const contentText = s.content.replace(/[#*_\-|]/g, '').trim();
    const firstSentence = contentText.split(/(?<=[.!?])\s+/)[0] || contentText.substring(0, 120);

    return `<div class="slide">
      <div class="exec-box">
        <div class="exec-label">Key Takeaway</div>
        <div class="exec-text">${firstSentence}</div>
      </div>
      <h2 class="slide-heading">${s.title}</h2>
      <div class="slide-body">${formatMarkdown(s.content)}</div>
    </div>`;
  }).join('\n');

  const css = `
    ${brandCSSVars(brand)}
    body {
      font-family: var(--brand-font-secondary);
      font-size: var(--brand-font-body-size);
      color: var(--brand-text);
      background: #f8f8f8;
      line-height: 1.7;
      -webkit-font-smoothing: antialiased;
    }
    .page {
      max-width: 900px;
      margin: 0 auto;
      padding: 48px 56px;
    }
    /* ── Cover ── */
    .cover {
      background: var(--brand-background);
      padding: 64px 56px;
      margin-bottom: 80px;
      border-left: 5px solid var(--brand-primary);
    }
    .cover-logo { margin-bottom: 40px; }
    .cover-title {
      font-family: var(--brand-font-primary);
      font-size: calc(var(--brand-font-h1-size) + 4px);
      font-weight: 700;
      color: var(--brand-primary);
      line-height: 1.15;
      margin-bottom: 12px;
    }
    .cover-subtitle {
      font-size: 16px;
      color: #888;
    }
    .cover-meta {
      margin-top: 32px;
      font-size: 13px;
      color: #999;
    }
    /* ── Slide sections ── */
    .slide {
      background: var(--brand-background);
      padding: 48px 56px;
      margin-bottom: 80px;
      page-break-inside: avoid;
    }
    .exec-box {
      background: #f3f4f6;
      border-left: 4px solid var(--brand-primary);
      padding: 20px 24px;
      margin-bottom: 32px;
    }
    .exec-label {
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: var(--brand-primary);
      margin-bottom: 6px;
    }
    .exec-text {
      font-size: 15px;
      font-weight: 500;
      color: var(--brand-text);
      line-height: 1.5;
    }
    .slide-heading {
      font-family: var(--brand-font-primary);
      font-size: var(--brand-font-h1-size);
      font-weight: 700;
      color: var(--brand-primary);
      margin-bottom: 24px;
      line-height: 1.2;
    }
    .slide-body p { margin-bottom: 14px; }
    .slide-body h1, .slide-body h2, .slide-body h3, .slide-body h4 {
      font-family: var(--brand-font-primary);
      color: var(--brand-primary);
      margin: 24px 0 10px;
    }
    .slide-body h2 { font-size: var(--brand-font-h2-size); }
    .slide-body h3 { font-size: var(--brand-font-h3-size); }
    .slide-body h4 { font-size: 14px; font-weight: 600; }
    .slide-body strong { font-weight: 600; }
    .slide-body ul, .slide-body ol { padding-left: 24px; margin: 12px 0; }
    .slide-body li {
      margin-bottom: 10px;
      font-size: 15px;
    }
    .slide-body hr { border: none; border-top: 1px solid #e5e5e5; margin: 24px 0; }
    .slide-body table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 13px;
    }
    .slide-body th {
      background: var(--brand-primary);
      color: #fff;
      font-weight: 600;
      text-align: left;
      padding: 10px 14px;
      font-size: 12px;
    }
    .slide-body td {
      padding: 9px 14px;
      border-bottom: 1px solid #eee;
    }
    /* ── Footer ── */
    .footer {
      text-align: center;
      font-size: 11px;
      color: #aaa;
      padding: 16px 0;
    }
  `;

  const body = `
    <div class="page">
      <div class="cover">
        <div class="cover-logo">${brandLogoHtml(input, 'height:36px;')}</div>
        <div class="cover-title">${title}</div>
        <div class="cover-subtitle">Prepared for ${input.prospect.companyName}</div>
        <div class="cover-meta">${dateStr}${input.prospect.industry ? ` | ${input.prospect.industry}` : ''}${input.prospect.companySize ? ` | ${input.prospect.companySize}` : ''}</div>
      </div>
      ${sectionsHtml}
      <div class="footer">${input.companyName} | ${dateStr} | Generated by ContentForg</div>
    </div>
  `;

  return wrapDocument({ title: `${title} — ${input.prospect.companyName}`, css, body, fonts: brandFonts(brand) });
}

// ── Thumbnail ───────────────────────────────────────────────

function thumbnail(accentColor: string): string {
  return `<div style="width:100%;height:100%;background:#f8f8f8;font-family:sans-serif;padding:16px 14px;box-sizing:border-box;position:relative;">
    <div style="background:#fff;border-left:4px solid ${accentColor};padding:12px 14px;margin-bottom:20px;">
      <div style="width:30px;height:6px;background:${accentColor};border-radius:1px;margin-bottom:8px;"></div>
      <div style="font-size:11px;font-weight:700;color:#222;margin-bottom:4px;">Document Title</div>
      <div style="width:60%;height:3px;background:#ddd;border-radius:1px;"></div>
    </div>
    <div style="background:#fff;padding:12px 14px;margin-bottom:20px;">
      <div style="background:#f3f4f6;border-left:3px solid ${accentColor};padding:6px 8px;margin-bottom:10px;">
        <div style="width:60%;height:3px;background:#ccc;border-radius:1px;margin-bottom:2px;"></div>
        <div style="width:40%;height:3px;background:#ccc;border-radius:1px;"></div>
      </div>
      <div style="font-size:9px;font-weight:700;color:${accentColor};margin-bottom:6px;">Section Title</div>
      <div style="width:90%;height:3px;background:#eee;border-radius:1px;margin-bottom:3px;"></div>
      <div style="width:80%;height:3px;background:#eee;border-radius:1px;margin-bottom:3px;"></div>
      <div style="width:85%;height:3px;background:#eee;border-radius:1px;"></div>
    </div>
    <div style="position:absolute;bottom:6px;left:0;right:0;text-align:center;font-size:6px;color:#aaa;">Company | Date | ContentForg</div>
  </div>`;
}

// ── Export ───────────────────────────────────────────────────

const style19ConsultingDeck: DocumentStyle = {
  id: 'style-19',
  name: 'Consulting Deck',
  category: 'corporate',
  description: 'Slide-like sections — large header, 3 bullets, executive takeaway boxes',
  keywords: ['consulting', 'deck', 'slides', 'mckinsey', 'takeaways', 'strategy'],
  render,
  thumbnail,
};

export default style19ConsultingDeck;
