import type { DocumentStyle, StyleInput } from './types';
import { resolveBrand, brandCSSVars, brandFonts, brandLogoHtml, formatMarkdown, wrapDocument } from './shared';

// ── Render ──────────────────────────────────────────────────

function render(input: StyleInput): string {
  const brand = resolveBrand(input);
  const dateStr = input.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const title = input.contentType.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  const sectionsHtml = input.sections.map(s => {
    return `<div class="section">
      <h2 class="section-heading">${s.title}</h2>
      <div class="section-body">${formatMarkdown(s.content)}</div>
    </div>`;
  }).join('\n');

  const css = `
    ${brandCSSVars(brand)}
    body {
      font-family: var(--brand-font-secondary);
      font-size: var(--brand-font-body-size);
      color: var(--brand-text);
      background: var(--brand-background);
      line-height: 1.65;
      -webkit-font-smoothing: antialiased;
    }
    .page {
      max-width: 880px;
      margin: 0 auto;
      padding: 56px 64px;
    }
    /* ── Header ── */
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
    }
    .header-meta {
      font-size: 12px;
      color: #888;
      text-align: right;
    }
    .title-bar {
      border-top: 1px solid #ccc;
      border-bottom: 1px solid #ccc;
      padding: 16px 0;
      margin-bottom: 40px;
    }
    .doc-title {
      font-family: var(--brand-font-primary);
      font-size: var(--brand-font-h1-size);
      font-weight: 600;
      color: var(--brand-text);
      letter-spacing: -0.01em;
    }
    .doc-subtitle {
      font-size: 13px;
      color: #888;
      margin-top: 4px;
    }
    /* ── Sections ── */
    .section {
      margin-bottom: 36px;
    }
    .section-heading {
      font-family: var(--brand-font-primary);
      font-size: 14px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      color: var(--brand-text);
      border-bottom: 1px solid #d0d0d0;
      padding-bottom: 6px;
      margin-bottom: 16px;
    }
    .section-body p { margin-bottom: 12px; }
    .section-body h1, .section-body h2, .section-body h3, .section-body h4 {
      color: var(--brand-text);
      margin: 20px 0 8px;
      font-weight: 600;
    }
    .section-body h2 { font-size: var(--brand-font-h3-size); }
    .section-body h3 { font-size: 14px; }
    .section-body h4 { font-size: 13px; }
    .section-body strong { font-weight: 600; }
    .section-body ul, .section-body ol { padding-left: 20px; margin: 10px 0; }
    .section-body li { margin-bottom: 5px; }
    .section-body hr { border: none; border-top: 1px solid #e5e5e5; margin: 20px 0; }
    /* ── Callout boxes ── */
    .section-body blockquote,
    .section-body h4 + p {
      border: 1px solid #e0e0e0;
      border-top: 3px solid var(--brand-accent);
      padding: 16px 20px;
      margin: 16px 0;
      background: #fafafa;
      font-size: 13px;
    }
    /* ── Tables — primary visual element ── */
    .section-body table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 13px;
    }
    .section-body th {
      background: #f5f5f5;
      font-weight: 600;
      text-align: left;
      padding: 10px 14px;
      border-bottom: 2px solid #ccc;
      font-size: 11px;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      color: #555;
    }
    .section-body td {
      padding: 9px 14px;
      border-bottom: 1px solid #eee;
      font-variant-numeric: tabular-nums;
    }
    .section-body tr:hover td {
      background: #f9f9fb;
    }
    /* ── Footer ── */
    .footer {
      margin-top: 48px;
      padding-top: 12px;
      border-top: 1px solid #ccc;
      font-size: 11px;
      color: #999;
      display: flex;
      justify-content: space-between;
    }
    .footer .disclaimer {
      font-style: italic;
      max-width: 500px;
    }
  `;

  const body = `
    <div class="page">
      <div class="header">
        <div>${brandLogoHtml(input, 'height:28px;')}</div>
        <div class="header-meta">${dateStr}</div>
      </div>
      <div class="title-bar">
        <div class="doc-title">${title}</div>
        <div class="doc-subtitle">${input.prospect.companyName}${input.prospect.industry ? ` | ${input.prospect.industry}` : ''}</div>
      </div>
      ${sectionsHtml}
      <div class="footer">
        <span>${input.companyName} | ${dateStr} | Generated by ContentForg</span>
        <span class="disclaimer">This document is confidential.</span>
      </div>
    </div>
  `;

  return wrapDocument({ title: `${title} — ${input.prospect.companyName}`, css, body, fonts: brandFonts(brand) });
}

// ── Thumbnail ───────────────────────────────────────────────

function thumbnail(accentColor: string): string {
  return `<div style="width:100%;height:100%;background:#fff;font-family:sans-serif;padding:20px 18px;box-sizing:border-box;position:relative;">
    <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
      <div style="width:40px;height:8px;background:#333;border-radius:1px;"></div>
      <div style="width:30px;height:4px;background:#ccc;border-radius:1px;"></div>
    </div>
    <div style="border-top:1px solid #ccc;border-bottom:1px solid #ccc;padding:8px 0;margin-bottom:16px;">
      <div style="font-size:11px;font-weight:600;color:#222;">Financial Report</div>
      <div style="width:50%;height:3px;background:#ddd;margin-top:4px;border-radius:1px;"></div>
    </div>
    <div style="font-size:7px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;border-bottom:1px solid #ddd;padding-bottom:4px;margin-bottom:8px;">Key Metrics</div>
    <div style="border:1px solid #e0e0e0;border-top:3px solid ${accentColor};padding:6px 8px;margin-bottom:12px;background:#fafafa;">
      <div style="width:60%;height:4px;background:#ddd;border-radius:1px;margin-bottom:3px;"></div>
      <div style="width:40%;height:4px;background:#ddd;border-radius:1px;"></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:2px;margin-bottom:3px;">
      <div style="height:5px;background:#f5f5f5;"></div>
      <div style="height:5px;background:#f5f5f5;"></div>
      <div style="height:5px;background:#f5f5f5;"></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:2px;margin-bottom:3px;">
      <div style="height:5px;background:#fafafa;"></div>
      <div style="height:5px;background:#fafafa;"></div>
      <div style="height:5px;background:#fafafa;"></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:2px;">
      <div style="height:5px;background:#f5f5f5;"></div>
      <div style="height:5px;background:#f5f5f5;"></div>
      <div style="height:5px;background:#f5f5f5;"></div>
    </div>
    <div style="position:absolute;bottom:8px;left:18px;right:18px;border-top:1px solid #ccc;padding-top:4px;font-size:6px;color:#aaa;">Company | Date | ContentForg</div>
  </div>`;
}

// ── Export ───────────────────────────────────────────────────

const style18FinancialReport: DocumentStyle = {
  id: 'style-18',
  name: 'Financial Report',
  category: 'corporate',
  description: 'Data tables, bordered callouts, understated headers — Goldman Sachs feel',
  keywords: ['financial', 'report', 'data', 'tables', 'metrics', 'research'],
  render,
  thumbnail,
};

export default style18FinancialReport;
